export const subjectsData = {
  biology: {
    name: "Biology",
    class11: [
      { id: "the-living-world", name: "The Living World", chapter: 1 },
      { id: "biological-classification", name: "Biological Classification", chapter: 2 },
      { id: "plant-kingdom", name: "Plant Kingdom", chapter: 3 },
      { id: "animal-kingdom", name: "Animal Kingdom", chapter: 4 },
      { id: "morphology-of-flowering-plants", name: "Morphology of Flowering Plants", chapter: 5 },
      { id: "anatomy-of-flowering-plants", name: "Anatomy of Flowering Plants", chapter: 6 },
      { id: "structural-organisation-in-animals", name: "Structural Organisation in Animals", chapter: 7 },
      { id: "cell-the-unit-of-life", name: "Cell: The Unit of Life", chapter: 8 },
      { id: "biomolecules", name: "Biomolecules", chapter: 9 },
      { id: "cell-cycle-and-cell-division", name: "Cell Cycle and Cell Division", chapter: 10 },
      { id: "transport-in-plants", name: "Transport in Plants", chapter: 11 },
      { id: "mineral-nutrition", name: "Mineral Nutrition", chapter: 12 },
      { id: "photosynthesis-in-higher-plants", name: "Photosynthesis in Higher Plants", chapter: 13 },
      { id: "respiration-in-plants", name: "Respiration in Plants", chapter: 14 },
      { id: "plant-growth-and-development", name: "Plant Growth and Development", chapter: 15 },
      { id: "digestion-and-absorption", name: "Digestion and Absorption", chapter: 16 },
      { id: "breathing-and-exchange-of-gases", name: "Breathing and Exchange of Gases", chapter: 17 },
      { id: "body-fluids-and-circulation", name: "Body Fluids and Circulation", chapter: 18 },
      { id: "excretory-products-and-their-elimination", name: "Excretory Products and Their Elimination", chapter: 19 },
      { id: "locomotion-and-movement", name: "Locomotion and Movement", chapter: 20 },
      { id: "neural-control-and-coordination", name: "Neural Control and Coordination", chapter: 21 },
      { id: "chemical-coordination-and-integration", name: "Chemical Coordination and Integration", chapter: 22 },
    ],
    class12: [
      { id: "reproduction-in-organisms", name: "Reproduction in Organisms", chapter: 1 },
      { id: "sexual-reproduction-in-flowering-plants", name: "Sexual Reproduction in Flowering Plants", chapter: 2 },
      { id: "human-reproduction", name: "Human Reproduction", chapter: 3 },
      { id: "reproductive-health", name: "Reproductive Health", chapter: 4 },
      { id: "principles-of-inheritance-and-variation", name: "Principles of Inheritance and Variation", chapter: 5 },
      { id: "molecular-basis-of-inheritance", name: "Molecular Basis of Inheritance", chapter: 6 },
      { id: "evolution", name: "Evolution", chapter: 7 },
      { id: "human-health-and-disease", name: "Human Health and Disease", chapter: 8 },
      {
        id: "strategies-for-enhancement-in-food-production",
        name: "Strategies for Enhancement in Food Production",
        chapter: 9,
      },
      { id: "microbes-in-human-welfare", name: "Microbes in Human Welfare", chapter: 10 },
      { id: "biotechnology-principles-and-processes", name: "Biotechnology: Principles and Processes", chapter: 11 },
      { id: "biotechnology-and-its-applications", name: "Biotechnology and Its Applications", chapter: 12 },
      { id: "organisms-and-populations", name: "Organisms and Populations", chapter: 13 },
      { id: "ecosystem", name: "Ecosystem", chapter: 14 },
      { id: "biodiversity-and-conservation", name: "Biodiversity and Conservation", chapter: 15 },
      { id: "environmental-issues", name: "Environmental Issues", chapter: 16 },
    ],
  },
  chemistry: {
    name: "Chemistry",
    class11: [
      { id: "some-basic-concepts-of-chemistry", name: "Some Basic Concepts of Chemistry", chapter: 1 },
      { id: "structure-of-atom", name: "Structure of Atom", chapter: 2 },
      {
        id: "classification-of-elements-and-periodicity",
        name: "Classification of Elements and Periodicity in Properties",
        chapter: 3,
      },
      { id: "chemical-bonding-and-molecular-structure", name: "Chemical Bonding and Molecular Structure", chapter: 4 },
      { id: "states-of-matter", name: "States of Matter", chapter: 5 },
      { id: "thermodynamics", name: "Thermodynamics", chapter: 6 },
      { id: "equilibrium", name: "Equilibrium", chapter: 7 },
      { id: "redox-reactions", name: "Redox Reactions", chapter: 8 },
      { id: "hydrogen", name: "Hydrogen", chapter: 9 },
      { id: "the-s-block-elements", name: "The s-Block Elements", chapter: 10 },
      { id: "the-p-block-elements", name: "The p-Block Elements", chapter: 11 },
      {
        id: "organic-chemistry-some-basic-principles-and-techniques",
        name: "Organic Chemistry - Some Basic Principles and Techniques",
        chapter: 12,
      },
      { id: "hydrocarbons", name: "Hydrocarbons", chapter: 13 },
      { id: "environmental-chemistry", name: "Environmental Chemistry", chapter: 14 },
    ],
    class12: [
      { id: "the-solid-state", name: "The Solid State", chapter: 1 },
      { id: "solutions", name: "Solutions", chapter: 2 },
      { id: "electrochemistry", name: "Electrochemistry", chapter: 3 },
      { id: "chemical-kinetics", name: "Chemical Kinetics", chapter: 4 },
      { id: "surface-chemistry", name: "Surface Chemistry", chapter: 5 },
      {
        id: "general-principles-and-processes-of-isolation-of-elements",
        name: "General Principles and Processes of Isolation of Elements",
        chapter: 6,
      },
      { id: "the-p-block-elements-group-15-to-18", name: "The p-Block Elements (Group 15 to 18)", chapter: 7 },
      { id: "the-d-and-f-block-elements", name: "The d- and f-Block Elements", chapter: 8 },
      { id: "coordination-compounds", name: "Coordination Compounds", chapter: 9 },
      { id: "haloalkanes-and-haloarenes", name: "Haloalkanes and Haloarenes", chapter: 10 },
      { id: "alcohols-phenols-and-ethers", name: "Alcohols, Phenols and Ethers", chapter: 11 },
      { id: "aldehydes-ketones-and-carboxylic-acids", name: "Aldehydes, Ketones and Carboxylic Acids", chapter: 12 },
      { id: "amines", name: "Amines", chapter: 13 },
      { id: "biomolecules", name: "Biomolecules", chapter: 14 },
      { id: "polymers", name: "Polymers", chapter: 15 },
      { id: "chemistry-in-everyday-life", name: "Chemistry in Everyday Life", chapter: 16 },
    ],
  },
  physics: {
    name: "Physics",
    class11: [
      { id: "physical-world", name: "Physical World", chapter: 1 },
      { id: "units-and-measurements", name: "Units and Measurements", chapter: 2 },
      { id: "motion-in-a-straight-line", name: "Motion in a Straight Line", chapter: 3 },
      { id: "motion-in-a-plane", name: "Motion in a Plane", chapter: 4 },
      { id: "laws-of-motion", name: "Laws of Motion", chapter: 5 },
      { id: "work-energy-and-power", name: "Work, Energy and Power", chapter: 6 },
      {
        id: "system-of-particles-and-rotational-motion",
        name: "System of Particles and Rotational Motion",
        chapter: 7,
      },
      { id: "gravitation", name: "Gravitation", chapter: 8 },
      { id: "mechanical-properties-of-solids", name: "Mechanical Properties of Solids", chapter: 9 },
      { id: "mechanical-properties-of-fluids", name: "Mechanical Properties of Fluids", chapter: 10 },
      { id: "thermal-properties-of-matter", name: "Thermal Properties of Matter", chapter: 11 },
      { id: "thermodynamics", name: "Thermodynamics", chapter: 12 },
      { id: "kinetic-theory", name: "Kinetic Theory", chapter: 13 },
      { id: "oscillations", name: "Oscillations", chapter: 14 },
      { id: "waves", name: "Waves", chapter: 15 },
    ],
    class12: [
      { id: "electric-charges-and-fields", name: "Electric Charges and Fields", chapter: 1 },
      { id: "electrostatic-potential-and-capacitance", name: "Electrostatic Potential and Capacitance", chapter: 2 },
      { id: "current-electricity", name: "Current Electricity", chapter: 3 },
      { id: "moving-charges-and-magnetism", name: "Moving Charges and Magnetism", chapter: 4 },
      { id: "magnetism-and-matter", name: "Magnetism and Matter", chapter: 5 },
      { id: "electromagnetic-induction", name: "Electromagnetic Induction", chapter: 6 },
      { id: "alternating-current", name: "Alternating Current", chapter: 7 },
      { id: "electromagnetic-waves", name: "Electromagnetic Waves", chapter: 8 },
      { id: "ray-optics-and-optical-instruments", name: "Ray Optics and Optical Instruments", chapter: 9 },
      { id: "wave-optics", name: "Wave Optics", chapter: 10 },
      { id: "dual-nature-of-radiation-and-matter", name: "Dual Nature of Radiation and Matter", chapter: 11 },
      { id: "atoms", name: "Atoms", chapter: 12 },
      { id: "nuclei", name: "Nuclei", chapter: 13 },
      {
        id: "semiconductor-electronics-materials-devices-and-simple-circuits",
        name: "Semiconductor Electronics: Materials, Devices and Simple Circuits",
        chapter: 14,
      },
      { id: "communication-systems", name: "Communication Systems", chapter: 15 },
    ],
  },
}

export type Subject = keyof typeof subjectsData
export type ClassLevel = "class11" | "class12"
export type Chapter = {
  id: string
  name: string
  chapter: number
}
